name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      
      - name: Publish to itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: web
          ITCH_GAME: morpion
          ITCH_USER: junkeecheese
          PATH: index.html


      - name: Notify Discord Channel
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.0
        with:
          args: 'A new update of my project is available at https://junkeecheese.itch.io/morpion. You should try it!'
