name: sybile-test-ci

on:
  push:
    branches: [ main ]

   
env:
  EXPORT_NAME: project-sybile
  GODOT_VERSION: 0.0.1

jobs:
  export-deploy:
    name: Web Export
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}