name: sybile-test-ci-2

on:
  push:
    branches: [ main ]

 
env:
  EXPORT_NAME: project-sybile


jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup
        run: |
          ls ${{ github.workspace }}
